language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --no-dev
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-9.5.19.phar

script:
  - php phpunit.phar

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml

notifications:
  email: false
